
时间：2017-01-03 21:37:47,159 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6378428 
System.Exception: {"fg":"1","x":"12","y":"6","l":"4"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-03 21:37:48,594 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6379863 
System.Exception: {"fg":"1","x":"6778","y":"3355","l":"13"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-03 21:38:19,129 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6410398 
System.Exception: {"fg":"6","x":"3389","y":"1677","l":"12"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-03 21:38:19,566 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6410835 
System.Exception: {"fg":"4","x":"3389","y":"1676","l":"12"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-03 21:39:04,757 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6456025 
System.Exception: {"fg":"4","x":"6777","y":"3354","l":"13"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-03 21:39:04,929 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6456198 
System.Exception: {"fg":"1","x":"6780","y":"3354","l":"13"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-03 21:40:37,443 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6548712 
System.Exception: {"fg":"2","x":"11","y":"4","l":"4"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---
